#!/usr/bin/python3 -IOO

from sys import path
from importlib import import_module


path.append('/usr/lib/bubblejail/python_packages')

import_module('bubblejail.bubblejail_cli'
              ).bubblejail_main()  # type: ignore
