#!/usr/bin/python3 -IOO

from sys import path


path.append('/usr/lib/bubblejail/python_packages')

if __name__ == "__main__":
    from bubblejail.bubblejail_cli import bubblejail_main
    bubblejail_main()
