#!/usr/bin/python3 -IOO

from sys import path
from importlib import import_module


path.append('/usr/lib/bubblejail/python_packages')


import_module('bubblejail.bubblejail_helper'
              ).bubblejail_helper_main()  # type: ignore
