# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024 igo95862
---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  linters:
    name: Run source code linters
    runs-on: ubuntu-latest
    container:
      image: docker.io/archlinux:latest
    steps:
      - name: Install linters and Python dependencies
        run: >
          pacman --noconfirm -Syu
          git
          python-pyflakes reuse
          mypy python-pyqt6 python-tomli-w
          python-black python-isort
          codespell
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add safe git directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run linters
        run: |
          python3 -m tools.run_linters

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: docker.io/archlinux:latest
    steps:
      - name: Install build dependencies
        run: >
          pacman --noconfirm -Syu
          git python python-jinja scdoc meson
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run meson
        run: |
          arch-meson -Dman=true build
          meson compile --verbose -C build
          meson install -C build --destdir install

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/archlinux:latest
    steps:
      - name: Install test dependencies
        run: >
          pacman --noconfirm -Syu
          git gcc python-jinja meson-python
          python python-pyxdg python-tomli-w python-cattrs
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Create venv
        run: |
          python -m tools.venv_setup
      - name: Run unit tests
        run: |
          ./venv/bin/python -m unittest
